# This is a basic workflow to help you get started with Actions

name: Pull Request Workflow

# Controls when the action will run.
on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # v2 minimum required
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'
  build:
    name: Build Robot Code
    runs-on: windows-2019
    needs: [check_style]
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # v2 minimum required
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Build
        shell: cmd
        run: ./gradlew build
