# This is a basic workflow to help you get started with Actions

name: Push Workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* 0 * * *'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build Robot Code
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # v2 minimum required
        with:
          ref: ${{ github.ref_name }}
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Build
        shell: cmd
        run: ./gradlew build
